version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing GCC, G++ and Make
          command: 'apt-get update && apt-get install -y gcc g++ make'
      - run:
          name: Build unit tests
          command: 'make tests'
      - run:
          name: Run Unit Tests
          command: './build/unittest.out'