version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing GCC and Make
          command: 'apt-get update && apt-get install -y gcc g++ make'
      - run:
          name: Build unit tests
          command: 'make test'
      - run:
          name: Run Unit Testing
          command: './build/unittest.out'