/*
 * intention_id_test.cpp
 *
 *  Created on: Jul 27, 2020
 *      Author: Matuzalem Muller
 */

#include "gtest/gtest.h"
#include "lib/intention_id.h"

class TIntentionID : public ::testing::Test
{
protected:
  IntentionID id_1;
  IntentionID * id_1_clone;
  IntentionID * id_2;

public:
  TIntentionID()
  {
    id_1_clone = &id_1;
    id_2 = new IntentionID();
  }

  ~TIntentionID()
  {
    delete id_2;
  }
};

/*
 * Confirm that IDs are generated by increment of 1
 */
TEST_F(TIntentionID, get_id)
{
  EXPECT_EQ(id_2->get_id(), id_1.get_id()+1);
}

/*
 * Test if is_equal method compares EventIDs correctly
 */
TEST_F(TIntentionID, is_equal)
{
  EXPECT_TRUE(id_1_clone->is_equal(id_1));
}
