# Image hosted at https://github.com/orgs/Embedded-BDI/packages/container/package/embeddedbdi-cicd
# Used for continuous integration on https://github.com/Embedded-BDI/embedded-bdi
FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y gcc g++ make doxygen graphviz valgrind git openjdk-11-jdk